server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hqms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    mode: HTML
#    cache: false
#    suffix: .html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/static/js/
mybatis:
  mapper-locations: classpath:mapping/**Mapper.xml
  #实体包路径别名
  #type-aliases-package: com.ts.demo.dao
